# Arquivo: docker/docker.yml

version: '3.8'

services:
  # Serviço do banco de dados (sem alterações necessárias aqui, além do caminho do volume)
  db:
    image: mariadb:10.6
    container_name: mariadb_agendamentos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      # CORREÇÃO: Apontar para o script SQL na pasta 'sql'
      - ../sql/entidades.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    env_file:
      - ../.env

  # Serviço da API Node.js
  api:
    container_name: api_agendamentos
    # CORREÇÃO: Apontar o contexto do build para a raiz do projeto (onde está o Dockerfile)
    build: ..
    restart: always
    ports:
      - '3001:3001'
    volumes:
      # Mapeia o código da aplicação para dentro do contêiner para desenvolvimento (hot-reload)
      # Qualquer alteração na pasta 'app' do seu PC será refletida no contêiner.
      - ../app:/usr/src/app/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3001
    networks:
      - app-network
    env_file:
      - ../.env

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
